---
- name: Install Apache2 and deploy static webpage
  hosts: ubuntu
  become: yes

  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 service is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy the static webpage to the web server
      copy:
        src: web/index.html    # The path to the local file
        dest: /var/www/html/index.html  # The destination on the remote server
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Check if the Apache2 server is running
      uri:
        url: http://localhost
        status_code: 200
